# -*- coding: utf-8 -*-
"""Programacion1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSWaJVRFIuvMKNbEeg0tX-v1s01-zqPu
"""

#CLASE 2 (24/08/2026)

#operaciones matematicas

vab1=20
vab2=15

print(vab1 + vab2)

print("La suma es:",vab1 + vab2)

vab1=20
vab2=15

suma= vab1 + vab2
resta= vab1 - vab2
multiplicacion= vab1 * vab2
Division= vab1 / vab2

print(vab1, "+" , vab2, "=", suma)
print(vab1, "-" , vab2, "=", resta)
print(vab1, "+" , vab2, "=", multiplicacion)
print(vab1, "/" , vab2, "=", Division)

nombre=input("indicanos tu nombre")

print("Por favor indicame 3 notas para calcular el promedio")

nota1=int(input("Nota 1: "))
nota2=int(input("Nota 2: "))
nota3=int(input("Nota 3: "))

suma= (nota1+nota2+nota3)
print("Suma de notas",suma)

nombre=input("indicanos tu nombre")

print("Por favor indicame 3 notas para calcular el promedio")

nota1=float(input("Nota 1: "))
nota2=float(input("Nota 2: "))
nota3=float(input("Nota 3: "))

suma= (nota1+nota2+nota3)
print("Suma de notas",suma)

nombre=input("indicanos tu nombre")

print("Por favor indicame 3 notas para calcular el promedio")

nota1=int(input("Nota 1: "))
nota2=int(input("Nota 2: "))
nota3=int(input("Nota 3: "))

suma= (nota1+nota2+nota3)
promedio= suma/36
print("Suma de notas",suma)
print("El promeio de notas es", promedio)

cantidad_productos = int(input("Ingrese la cantidad de productos comprados: "))
precio_unitario = float(input("Ingrese el precio unitario de cada producto: "))

subtotal = cantidad_productos * precio_unitario
iva = subtotal * 0.19
total_a_pagar_sin_descuento = subtotal + iva
descuento = subtotal * 0.10
total_final = total_a_pagar_sin_descuento - descuento

print(f"\nSubtotal de la compra: ${subtotal:.2f}")
print(f"Valor del IVA (19%): ${iva:.2f}")
print(f"Total a pagar (sin descuento): ${total_a_pagar_sin_descuento:.2f}")
print(f"Valor del descuento (10% sobre subtotal): ${descuento:.2f}")
print(f"Total final a pagar (con descuento e IVA): ${total_final:.2f}")

"""Ejercicio 1 — Cafetería universitaria (2,5 puntos)

Una cafetería universitaria desea automatizar el cálculo de una compra. El programa debe solicitar al usuario la cantidad de productos comprados y el precio unitario de cada producto.

El programa debe:

* a. (0,5 puntos): Calcular y mostrar el subtotal de la compra.
* b. (0,5 puntos): Calcular y mostrar el 10% de descuento aplicado sobre el subtotal.
* c. (0,5 puntos): Calcular y mostrar el IVA del 19% sobre el subtotal.
* d. (0,5 puntos): Calcular y mostrar el total a pagar después del descuento y antes del IVA.
* e. (0,5 puntos): Calcular y mostrar el valor final a pagar, incluyendo el IVA.

"""

print("BIENVENIDO A LA CAFETERIA UNAB")

cantidad = int(input("Ingrese la cantidad de productos comprados: "))

precio = float(input("Ingrese el precio unitario de cada producto: "))

subtotal = cantidad * precio
descuento = subtotal * 0.10
total_descuento = subtotal - descuento
iva = total_descuento  * 0.19
total_final = total_descuento + iva


print("subtotal de la compra: $", subtotal)
print("descuento del 10%: $", descuento)
print("valor del iva (19%) : $", iva)
print("Total con descuento : $ ", total_descuento)
print("Total final: $", total_final)

"""Ejercicio 2 — Viaje en automóvil (2,5 puntos)

Una persona desea calcular cuánto dinero gastará en combustible durante un viaje. Para ello, conoce la distancia del viaje en kilómetros, el rendimiento del automóvil en kilómetros por litro y el precio de un litro de gasolina.

El programa debe:

* a. (0,5 puntos): Calcular y mostrar la cantidad de litros de gasolina necesarios para realizar el viaje.
* b. (0,5 puntos): Calcular y mostrar el costo total del combustible.
* c. (0,5 puntos): Calcular y mostrar el costo del combustible si el precio aumenta un 8%.
* d. (0,5 puntos): Calcular y mostrar cuánto corresponde pagar si el costo total se divide entre 3 personas.
* e. (0,5 puntos): Calcular y mostrar el costo total del viaje ida y vuelta.
"""

print("Viaje em automovil")

kilometros = float(input("Ingrese la cantidad de kilometros: "))
rendimiento_km_por_litro = float(input("Ingrese el rendimiento del automóvil (km por litro): "))
precio_litro_gasolina = float(input("Ingrese el precio de un litro de gasolina: "))


litros_necesarios = kilometros / rendimiento_km_por_litro
print("Cantidad de litros de gasolina necesarios:",litros_necesarios , "litros")


costo_total_combustible = litros_necesarios * precio_litro_gasolina
print("Costo total del combustible: $",costo_total_combustible)


precio_aumento_8_porciento = precio_litro_gasolina * 8/100
costo_con_aumento = litros_necesarios * precio_aumento_8_porciento
print("Costo del combustible con un aumento del 8%: $",costo_con_aumento)


costo_por_persona = costo_total_combustible / 3
print("Costo por persona (dividido entre 3): $",costo_por_persona)

costo_ida_y_vuelta = costo_total_combustible * 2
print("Costo total del viaje ida y vuelta: $",costo_ida_y_vuelta)

"""CLASE 07/*09*

CICLOS FOR Y WHILE
"""

num1 = int(input("Dame un numero"))
num2 = int(input("Dame un numero"))
num3 = int(input("Dame un numero"))

suma=num1+num2+num3

print("La suma es: ", suma)

CuantosNumerosSumar= int(input("¿Cuantos numeros deas sumar?"))

acumuladoSuma= 0

for i in range (CuantosNumerosSumar):
  numero=int(input("Dame el numero que quieres sumar"))
  acumuladoSuma= acumuladoSuma + numero
print("La suma es", acumuladoSuma)

for i in range(5):
  print("i =", i)

for i in range (3):
  print("Esta por dentro el bucle:", i , "vez")
print("Esta por fuera")

#Caso 1
print("#Caso 1")
for i in range(5):
   print("i=", i)

#Caso 2
print("#Caso 2")
for i in range(1,5):
   print("i=", i)

#Caso 3
print("#Caso 3")
for i in range(1,5,2):
   print("i=", i)

# Ejercicio 1
notas=(3.5, 4.2, 2.8, 5.0)

for nota in notas:
   print("La nota es:", nota)

#Ejercicio 2
notas= (3.5, 4.2, 2.5, 5.0)
suma= 0

for nota in notas:
    suma= suma + nota
print("Promedio:", suma / len(notas))

#Cuenta regresiva
n= 5
while n > 0:
     print(n)
     n= n - 1
print("¡Despegue!")

#Validar Edad
edad=int(input("Tu edad :"))

while edad < 0:
    print("Eso no es valido")
    edad= int(input("Tu edad:  "))

#Validar Edad
edad=int(input("Tu edad :"))

while edad < 1 and :
    print("Eso no es valido")
    edad= int(input("Tu edad:  "))
print ("Bienvenido")

#Ejercicio de practica parcial

edad= int(input("Digite su edad: "))


if edad >= 18:
    print("Es mayor de edad")
else:
   print("Es menor de edad")

# Ejercicio 2

numero = int(input("Digite su numero:"))

if numero > 0:
   print("Es positivo")

elif numero < 0:
   print("Es negativo")

else:
   print("cero")

#Ejercicio 3

for i in range (1,7):
     print(i)

#Ejercicio 4

numero = int(input("Digite el numero: "))
for i in range(1,6):
    print(numero * i)

#Ejercicio 5

numero= int(input("Por favor digite su numero: "))

while numero != 0:

      print(numero)
      numero= int(input("Digite otro numero: "))

#Ejercicio 6
numero = int(input("Por favor digite el numero: "))
contador = 0
while numero != 0:
      print(numero)
      contador = contador + 1
      numero= int(input("Digite otro numero: "))
print("ingresaste",contador,"numeros")

#Ejercicio de tarea (Imprime los numeros del 1 al 20 , uno debajo del otro)

for numero in range(1,21):
     print(numero)

#Ejercicio 2 (Imprime la tabla de multiplicar del 7 empezando en 7*1 hasta 7*10)

for numero in range (1, 11):
    print("7 x", numero ,"=",7*numero)

#Ejercicio 3 (Dada la lista de precios (1200,3500,800)calcular e imprimir el total)

precios = [1200, 3500, 800]
total = 0

for precio in precios:
    total += precio

print("El total es: ", total)

#Ejercicio 4 (Pide un numero al usuario hasta que escriba un positivo)

numero= int(input("Escriba un numero positivo"))

while numero <= 0:
    numero= int(input("Debe ser positivo. Intenta otra vez"))

print("¡Correcto!")

#Ejercicio 5 (Cuenta regresiva)

numero = 10

while numero >= 1:
     print(numero)
     numero -=1

print("Feliz Año")

# Ejercicio 6 (Numeros pares del 1 al 30)

for numero in range (2, 31, 2):
     print(numero)

#Practica

for numero in range (1,11):
    print(numero)

#Ejericico2

for numero in range (10, 0, -1):
    print(numero)

#Ejercicio 3

for numero in range (5, 51, 5):
    print(numero)

#Ejercicio 4:

for numero in range (2, 21, 2):
    print(numero)

#Ejercicio 5:

numero = int(input("Escriba un numero: "))

for i in range (1,11):
    print(numero, "x" , "=" , numero*i)

edad = int(input("Ingrese su edad: "))

if edad < 0:
    print("Edad no válida")

elif edad <= 12:
    print("Niño")

elif edad <=17:
    print("adolecente")

elif edad <=59:
    print("adulto")

else:
    print("aulto mayor")

nota = float(input("Ingrese su nota final (0.0 a 5.0): "))

if nota < 0.0 or nota > 5.0:
    print("Valor fuera de rango")

elif nota >= 3.0:
    print("Aprobó")

elif nota >= 2.5 and nota <=2.99:
    print("Habilitacion")

else:
    print("Reprobo")

rol = input("Ingrese su rol (estudiante/docente/administrador): ")

if rol == "estudiante" or rol == "Estudiante" or rol == "ESTUDIANTE":
    print("Bienvenido/a estudiante")
elif rol =="docente" or rol == "Docente" or rol == "DOCENTE":
    print("Bienvenido/a docente")
elif rol =="administrador" or rol == "Administrador" or rol == "ADMINISTRADOR":
    print("Bienvenido/a administrador")
else:
    print("Rol no reconocido")

peso = float(input("Ingrese su peso en kg: "))
estatura = float(input("Ingrese su estatura en metros: "))
imc = peso / (estatura ** 2)
estatura = estatura ! 0:

if imc < 18.5:
    print("Bajo peso")
elif imc <=24.9:
    print("Peso normal")
elif imc <=29.9:
    print("Sobrepeso")
else:
    print("Obesidad")

compra = float(input("Ingrese el valor de la compra: "))
respuesta = input("¿Es estudiante? (si/no): ")
es_estudiante = respuesta == "si"

descuento = 0.0
if es_estudiante:
    descuento += 0.15

if compra > 200000:
    descuento += 0.05

valor_descuento = compra * descuento
valor_final = compra - valor_descuento

print("Descuento aplicado:", descuento * 100, "%")
print("Valor final a pagar: $", valor_final)

"""ESTRUCURAS DE DATOS

"""

listaNumeros = [2, 3.5, 4, 80]

print(type(listaNumeros))
print("Tamaño usta ->",len(listaNumeros))
i=80
print(listaNumeros)
print("Los valores en la lista son :")
i=0
for valor in listaNumeros :
   print("listaNumeros[",i, "] =",valor)
   i+=1

listaFrutas =["manzana", "pera", "fresa"]
print(listaFrutas)

listaFrutas[1]="mango"
print(listaFrutas)

listaDatosPersonales = ["Silvia moreno", 29,1.67, "julianamroa@gmail.com", " cra 2 22 222", "barrio imaginario"]

print(listaDatosPersonales)

print("FORMULARIO GENERICO")
nombre= input("Indicame tu nombre: ")
edad=int(input("Dame tu edad: "))
altura=float(input("Dame tu altura"))
correo= input("Ingresa tu correo: ")
direccion= input("Ingresa tu direccion: ")
barrio= input("Ingresa tu barrio: ")

listaUsuario = [nombre, edad, altura, correo, direccion, barrio]
print(listaUsuario)

grupoClase = [listaUsuario,listaUsuario,listaUsuario,listaUsuario]
print(grupoClase)

"""Enunciado
Doña Marta tiene una tienda de barrio y recibe pedidos por WhatsApp. Para no perder el hilo, guarda cada pedido en una sola lista con estos datos, en este orden: el nombre del cliente (texto), el número de productos (entero), el total a pagar (decimal), si ya pagó (verdadero o falso) y la dirección de entrega (texto). El pedido de hoy es el de Laura:
pedido = ["Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"]
Durante la mañana el pedido va cambiando y doña Marta necesita que tu programa lo vaya actualizando sobre la misma lista, sin volver a crearla desde cero. Sigue las instrucciones en orden y usa un print para mostrar el resultado de cada paso.
Qué debe hacer tu programa
1. Crea la lista e imprime el nombre del cliente (índice positivo) y la dirección de entrega (índice negativo, sin contar cuántos elementos hay).
2. Laura agregó dos productos más y el total subió a $62.300. Además, ya pagó por transferencia. Corrige esos tres datos directamente en sus posiciones.
3. Doña Marta quiere guardar el teléfono de Laura, "3001234567" (como texto), justo después del nombre, y el nombre del domiciliario, "Andrés", al final de la lista.
4. Agrega al final la hora estimada de entrega: 10 (hora) y 30 (minutos), cada uno como un elemento independiente de la lista. Imprime la lista completa y cuántos elementos tiene.
5. Usando :, imprime en un print distinto cada uno de estos cortes: (a) nombre y teléfono; (b) número de productos, total y estado de pago; (c) los tres últimos datos; (d) toda la lista en orden inverso.
Entrega: escribe el programa en Python, ejecútalo y anexa una captura de pantalla del código y otra del resultado impreso en consola.
Preguntas trampa
A. Un compañero resolvió el paso 4 con otra instrucción y su lista quedó con 8 elementos en vez de 9. ¿Qué hizo diferente y qué obtiene al imprimir el último elemento de su lista?

B. Otro compañero, ya hecho el paso 3, escribe pedido[4] esperando obtener la dirección de entrega. ¿Qué valor y de qué tipo recibe realmente, y por qué dejó de ser la dirección?


"""

pedido = ["Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"]

print("Nombre cliente: ", pedido[0])
print("Direccion: ", pedido[-1])

pedido[1]= 5
pedido[2]= 62300
pedido[3]= True

print(pedido)


pedido = ["Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"]
pedido[1]= pedido[1] + 2
pedido[2]= pedido[2] + 16800
pedido[3]= True

print(pedido)

pedido.insert(1, "3001234567")
print(pedido)

pedido.append("Andres")
print(pedido)

pedido.append([10,30])
print(pedido)
print(len(pedido))


print("Primer mensaje")
print(pedido[:2])

print("Segundo mensaje")
print(pedido[2:5])

print("Tercer mensaje")
print(pedido[-3:])

print("Cuarto mensaje")
print(pedido[::-1])

listaNumeros = [5,50,100,200]

print(listaNumeros)

for num in listaNumeros:
  print(num)

print(len(lis))

for i in range(4):
  print("listaNumeros[",i,"]=", listaNumeros[i])